import Head from "next/head";
import { StyledLayout, StyledChildren, StyledFooter } from "./styles.js";

const AppLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledLayout>
        <header>
          <nav>NAVBAR IN PROGRESS LALA </nav>
        </header>
        <StyledChildren>{children}</StyledChildren>
        <StyledFooter>Footercito</StyledFooter>
      </StyledLayout>
    </>
  );
};

export default AppLayout;
