import Head from "next/head";
import Link from "next/link";
import {
  StyledLayout,
  StyledChildren,
  StyledFooter,
  StyledNav,
} from "./styles.js";

const AppLayout = ({ children, showNavbar = true }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledLayout>
        {showNavbar && (
          <header>
            <StyledNav>
              <ul>
                <li>
                  <Link href="/home">
                    <a>Home</a>
                  </Link>
                </li>
                <li>
                  <Link href="/about">
                    <a>About</a>
                  </Link>
                </li>
              </ul>
            </StyledNav>
          </header>
        )}
        <StyledChildren>{children}</StyledChildren>
        <StyledFooter>Powered by NextJS</StyledFooter>
      </StyledLayout>
    </>
  );
};

export default AppLayout;
